### ISSUE TITLE
Problem on database connection to PostgreSQL 8.3

### ISSUE THREAD

**Issue by vincechan15** [dreamfactorysoftware/dsp-core#102]
I got the following error when trying to call GET /db/{table_name} operation ( getRecordsByFilter() - Retrieve one or more records by using a filter).

```
[app][ERROR    ] CDbCommand::fetchAll() failed: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "field_name"
LINE 1:   SELECT k.column_name field_name
                               ^. The SQL statement executed was:       SELECT k.column_name field_name
            FROM "information_schema"."key_column_usage" k
            LEFT JOIN "information_schema"."table_constraints" c
              ON k.table_name = c.table_name
             AND k.constraint_name = c.constraint_name
           WHERE c.constraint_type ='PRIMARY KEY'
                AND k.table_name = :table
                AND k.table_schema = :schema.  
```

Please refer to my question on http://stackoverflow.com/questions/32522063/dreamfactory-database-connection-to-postgres/32582697#32582697

Is it related to PostgreSQL version?

**Comment by jstablesdf** [comment]
What server environment do you have DreamFactory installed in? Did you install with a Bitnami package, or direct from source? What leads you to think this is due to the DB version? What version of PostgreSQL are you connecting to? Are you able to connect to other versions of PostgreSQL?

**Comment by vincechan15** [comment]
DSP version : 1.9.4 Installed with a Bitnami package
I have tested to connect to PostgreSQL version 9 which is success. And it is fail for version 8.3

**Comment by vincechan15** [comment]
Is there a patch on this bug??

**Comment by jstablesdf** [comment]
Since it's proven that current versions of PostgreSQL work fine, I do not believe we will be going back to version 1.x to add support for legacy PostgreSQL versions. You should use version 9+. PostgreSQL 8.3 is from 2008 and reached end-of-life in December 2013. I recommend using up-to-date versions of PostgreSQL. If you need to support legacy data via pgsql, I recommend requesting a feature added or contributing this integration to DreamFactory 2.0.
