### ISSUE TITLE
Schema Manager changes not persistent

### ISSUE THREAD

**Issue by spackmat** [dreamfactorysoftware/dsp-core#59]
Hi,

when I edit a Schema in JSON view and save it, my changes are reflected to the table view. But when I get back later and edit the JSON view again, some of my changes are set back, others are kept.

E.g.:
The *supports_multibyte* is sooner or later set back to false on all fields and an *enum* field type is set back to string(x) (which also reflects to the underlying database, thank you). One of my tables cannot hold its new label and is always set back to its auto-set label, despite other tables can hold their changed label. Maybe there are other changes reverted, but I found those for now.

What is wrong here?

**Comment by jstablesdf** [comment]
This was fixed and released in 1.9.0 https://github.com/dreamfactorysoftware/dsp-core/commit/9d53a264ec2b98ec1f0f516648ac917877cf5b89

Fixed for "supports_multibyte" in the platform and yii libraries. The other two mentioned are not reproducible and may have been fixed in the develop branch prior to the release of 1.9.0.

Note that PostgreSQL doesn't support this feature directly as the collation/character set is set elsewhere (DB level) and not accessible currently.
