### ISSUE TITLE
Data filtering using private lookup key is impossible

### ISSUE THREAD

**Issue by cyberXndr** [dreamfactorysoftware/dsp-core#72]
It's not possible to filter data from the table using private lookup key. For example if I have ```Products``` table with ```company_key``` char field it's not possible to apply access filter ```company_key = {company_key}``` based on the role lookup key. The same thing works well if the role lookup key is not marked as private.
I don't found this moment in the documentation, so it seems to be like a little enhancement (rather than bug).

**Comment by leehicks** [comment]
You are correct. Lookup keys that are used in service credentials or headers and parameters on remote web services must be marked private due to the fact that those credentials or parameters typically carry things that should be private like passwords or API keys. 

Currently, lookup keys used in database transactions can not use private keys due to the fact that you could simply write the key to a record using field value replacement and read it back to get the value of the key, which would make them not so private for client use.

However I do see your point, using them in filters could be advantageous and would not necessarily expose them to the client. I will file this for consideration in 2.0. Thanks for the suggestion.
